# This workflow will install Python dependencies, run a Python script
# 
name: Say gm at 9:00 everyday 

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 9 * * *" # run task At 09:00 everyday

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python script # run Python script: .py
      run: python3 main.py
      env:
        AUTH: ${{ secrets.AUTH }}
